### ISSUE TITLE
Enable docker images to run as non root user

### ISSUE THREAD

**Issue by petenorth** [jaegertracing/jaeger-openshift#44] opened 2017-12-01 15:36 UTC
Currently the jaeger images run as root which means that they will not run on Openshift (other than installs where it is configured to be allowed such as minishift with the anyuid plugin).

The required approach is documented here

https://docs.openshift.com/container-platform/3.5/creating_images/guidelines.html

in the section 'Support Arbitrary User IDs'.

A common approach when encountering an image that runs as root is to create a derived image which runs necessary commands

RUN chgrp -R 0  <directory>
RUN chmod -R g+rw  <directory>

but this is problematic with the jaeger images as their base image is 'scratch' which does not have a shell installed etc.

Peter.

**Comment by objectiser** [comment] 2017-12-01 17:11
@kevinearls Is the CI job using minishift? or full openshift? Just wondering why we would not have seen this before.

@petenorth Would just setting the user to a random user work? i.e. as described in https://github.com/openshift-evangelists/openshift-workshops/blob/master/modules/run-as-non-root.adoc

As this would still enable the image to remain based on SCRATCH.

**Comment by petenorth** [comment] 2017-12-01 17:17
@objectiser the permissions still need to change, in the Dockerfile used in the example you quoted it still has

RUN rm -rf /run/httpd && mkdir /run/httpd && chmod -R a+rwx /run/httpd

and rm, mkdir and chmod will not be available in scratch .

I have just managed to build jaeger so may well be able get a Docker file up and running (probably based on centos/RHEL) at some point.

**Comment by objectiser** [comment] 2017-12-01 17:28
If you can work out what would be a minimal Dockerfile for each of the components, possibly starting with the all-in-one, then it might be possible to get the change applied in the main repo, rather than maintaining separate Dockerfiles.

The component Dockerfiles were originally based on centos:7, so don't think it would be a problem to pick a suitable base.

**Comment by petenorth** [comment] 2017-12-03 11:23
@objectiser I've come across this post

https://medium.com/@lizrice/non-privileged-containers-based-on-the-scratch-image-a80105d6d341

but it requires Docker daemon and client versions of 17.05 which will be a hassle but should be able to upgrade.

Then the Dockerfile I have in mind will look like (resulting in an centos 7 based image rather than scratch)

`FROM jaegertracing/all-in-one

FROM centos:7

# Agent zipkin.thrift compact
EXPOSE 5775/udp

# Agent jaeger.thrift compact
EXPOSE 6831/udp

# Agent jaeger.thrift binary
EXPOSE 6832/udp

# Agent config HTTP
EXPOSE 5778

# Collector HTTP
EXPOSE 14268

# Web HTTP
EXPOSE 16686

COPY --from=0 /go/src/jaeger-ui-build /go/src/jaeger-ui-build
COPY --from=0 /go/bin/ /go/bin/


RUN chgrp -R 0  /go/src/jaeger-ui-build
RUN chmod -R g+rw  /go/src/jaeger-ui-build

RUN chgrp -R 0  /go/bin/
RUN chmod -R g+rwx  /go/bin/

RUN useradd -u 10001 scratchuser
USER scratchuser

CMD ["/go/bin/standalone-linux","--span-storage.type=memory","--query.static-files=/go/src/jaeger-ui-build/build/"]
`

**Comment by petenorth** [comment] 2017-12-03 15:15
In fact a much simpler Dockerfile can be used

`FROM jaegertracing/all-in-one`
`USER 10001`
`CMD ["/go/bin/standalone-linux","--span-storage.type=memory","--query.static-files=/go/src/jaeger-ui-build/build/"]`

Though what I now get I think are UDP related errors? (a more restrictive Openshift environment will not allow UDP)

{"level":"error","ts":1512313799.8803618,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"127.0.0.1:0","connCheckTimeout":0.25,"error":"dial tcp 127.0.0.1:0: getsockopt: connection refused","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}

Which might be more troublesome to resolve.

**Comment by petenorth** [comment] 2017-12-04 09:37
Is something like

**Comment by kevinearls** [comment] 2017-12-05 10:57
@objectiser Our CI job is using a real openshift cluster, not minishift.  I've checked with our admin, and it's not running as root, so I don't know why I haven't run into this problem.

@petenorth  We are testing templates on our CI using the Jenkinsfile in jenkins-ci of https://github.com/jaegertracing/jaeger-openshift . Is there anything I'm doing that would allow this to work for me where it's failing for you?

(If you want to try it yourself there's a shortened version of the Jenkinsfile here https://gist.github.com/kevinearls/d95059848cb36bc6372ee28190ca3b7a which has the notification step remove, and doesn't delete Jaeger at the end.  It just requires a jdk name 'jdk8' and maven-3.5.2.)

**Comment by petenorth** [comment] 2017-12-05 15:11
@kevinearls can attach the security context section (for the container)  of the output of a curl command?

To get the the bear token issue the following command

`oc whoami --show-token=true`

then

` curl -X GET -H "Authorization: Bearer <bearer token>" 'https://<host>:<port>/api/v1/namespaces/<your namespace>/pods?labelSelector=app=jaeger' --insecu`re

It should look something like 

            "securityContext": {
              "capabilities": {
                "drop": [
                  "KILL",
                  "MKNOD",
                  "SETGID",
                  "SETUID",
                  "SYS_CHROOT"
                ]
              },
              "privileged": false,
              "seLinuxOptions": {
                "level": "s0:c21,c10"
              },
              "runAsNonRoot": true
            }

**Comment by kevinearls** [comment] 2017-12-06 15:06
@petenorth I've sent you an email, please let me know if you need anything else.

**Comment by petenorth** [comment] 2017-12-06 15:22
Will do, probably will be able to take a look tomorrow.

**Comment by jpkrohling** [comment] 2018-01-30 14:46
@petenorth , @kevinearls , any updates on this? I never faced any issue with Jaeger images on OpenShift and I'm surprised it wouldn't work there, as it's our main runtime for those images :)

**Comment by kevinearls** [comment] 2018-02-01 09:51
@jpkrohling I emailed @petenorth on this and in the last message I got from him he thought the cause of the problem might have been the admins on the OpenShift instance he was using had done something to change the security context.  I've never had a problem with this, and was not able to reproduce what he was seeing.

**Comment by jpkrohling** [comment] 2018-02-01 10:12
Awesome, I'm closing this one then. Feel free to reopen if it's indeed a problem.

**Closed by jpkrohling** 2018-02-01 10:12 UTC
